---
# Install Apache HTTPD
- name: Install Apache HTTPD
  ansible.builtin.yum:
    name: httpd
    state: present

# Start and enable Apache service
- name: Start and enable Apache service
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: true
